# Use the image built by your original Dockerfile as the base
FROM document_pipeline:latest

ARG PRINTER_IP
# Install additional packages
RUN apk add --no-cache libwebp-tools imagemagick ghostscript

# Newer versions of sane don't work with ADF Duplex scanning correctly.
# Install sane version 1.0 from alpine 3.10 repository.
RUN echo https://dl-cdn.alpinelinux.org/alpine/v3.10/main >> /etc/apk/repositories
RUN echo https://dl-cdn.alpinelinux.org/alpine/v3.10/community >> /etc/apk/repositories
RUN apk update && apk add "sane=~1.0" "sane-utils=~1.0" "sane-backend-pixma=~1.0"
RUN echo "bjnp://$PRINTER_IP" >> /etc/sane.d/pixma.conf

# You can add any other customizations here

# Optionally, you can override the entrypoint or cmd if needed
# ENTRYPOINT ["/custom-entrypoint.sh"]
# CMD ["custom-start"]
